# Generated by Django 6.0.5 on 2026-05-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pnl_usd', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('profitable_trades', models.PositiveIntegerField(default=0)),
                ('discarded_opportunities', models.PositiveIntegerField(default=0)),
                ('failed_trades', models.PositiveIntegerField(default=0)),
                ('total_fees_usd', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('average_execution_time_ms', models.PositiveIntegerField(default=0)),
                ('win_rate_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
