# Generated by Django 6.0.5 on 2026-05-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('best_bid', models.DecimalField(decimal_places=8, max_digits=20)),
                ('best_ask', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid_volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('ask_volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('spread', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange')),
            ],
        ),
    ]
