# Generated by Django 6.0.5 on 2026-05-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_available', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('usdt_available', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('btc_locked', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('usdt_locked', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_value_usd', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='WalletMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(max_length=30)),
                ('asset', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('balance_before', models.DecimalField(decimal_places=8, max_digits=24)),
                ('balance_after', models.DecimalField(decimal_places=8, max_digits=24)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='wallets.wallet')),
            ],
        ),
    ]
