# Generated by Django 6.0.5 on 2026-05-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arbitrage', '0001_initial'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('quantity_btc', models.DecimalField(decimal_places=8, max_digits=20)),
                ('buy_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sell_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('buy_cost', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sell_revenue', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_fees', models.DecimalField(decimal_places=8, max_digits=20)),
                ('slippage_cost', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('latency_cost', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('executed', 'Ejecutada'), ('partially_executed', 'Ejecutada parcialmente'), ('failed', 'Fallida'), ('discarded', 'Descartada')], max_length=30)),
                ('executed_at', models.DateTimeField()),
                ('buy_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='exchanges.exchange')),
                ('opportunity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arbitrage.arbitrageopportunity')),
                ('sell_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='exchanges.exchange')),
            ],
        ),
    ]
