# Generated by Django 6.0.5 on 2026-05-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('websocket_url', models.URLField(blank=True, null=True)),
                ('trading_fee_percent', models.DecimalField(decimal_places=5, default=0.1, max_digits=8)),
                ('withdrawal_fee_btc', models.DecimalField(decimal_places=8, default=0.0005, max_digits=18)),
            ],
        ),
    ]
