# Generated by Django 6.0.5 on 2026-05-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume_available', models.DecimalField(decimal_places=8, max_digits=20)),
                ('gross_spread', models.DecimalField(decimal_places=8, max_digits=20)),
                ('gross_spread_percent', models.DecimalField(decimal_places=6, max_digits=10)),
                ('estimated_fees', models.DecimalField(decimal_places=8, max_digits=20)),
                ('estimated_slippage', models.DecimalField(decimal_places=8, max_digits=20)),
                ('withdrawal_cost', models.DecimalField(decimal_places=8, max_digits=20)),
                ('latency_penalty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('net_profit_percent', models.DecimalField(decimal_places=6, max_digits=10)),
                ('status', models.CharField(max_length=30)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('buy_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_opportunities', to='exchanges.exchange')),
                ('sell_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_opportunities', to='exchanges.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityCostBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_fee_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('sell_fee_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('withdrawal_fee_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('slippage_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('latency_penalty_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdown', to='arbitrage.arbitrageopportunity')),
            ],
        ),
    ]
