# Generated by Django 6.0.5 on 2026-05-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume_available', models.DecimalField(decimal_places=8, max_digits=20)),
                ('gross_spread', models.DecimalField(decimal_places=8, max_digits=20)),
                ('estimated_fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('estimated_slippage', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('latency_penalty', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('net_profit_percent', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('detected', 'Detectada'), ('profitable', 'Rentable'), ('discarded', 'Descartada'), ('executed', 'Ejecutada'), ('failed', 'Fallida')], default='detected', max_length=20)),
                ('detected_at', models.DateTimeField()),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('buy_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_opportunities', to='exchanges.exchange')),
                ('sell_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_opportunities', to='exchanges.exchange')),
            ],
        ),
    ]
